---
title: "TCGA SKCM gene signature survival"
author: "Georgios Fotakis"
date: "2024-11-20"
output: html_document
---

Load libraries

```{r include=FALSE}
library(survival)
library(survminer)
library(dplyr)
library(GSVA)
library(tidyr)
library(conflicted)
conflict_prefer("select", "dplyr")
```

Load in the data

```{r}
clinical <- read.csv2("/home/fotakis/myScratch/projects/Sophie_Patti/clinical/clinical.tsv",
                      header = T,
                      sep = "\t")

expression.clean <- read.csv2("/home/fotakis/myScratch/projects/Sophie_Patti/counts_total/SKCM_TPM.tsv",
                              header = T,
                              sep = "\t")

mappings <- read.csv("/home/fotakis/myScratch/projects/Sophie_Patti/gdc_sample_sheet.2024-10-14.tsv",
                     header = T,
                     sep = "\t")
```

Helper Functions

```{r}
# Function to clean up the column names
clean_column_names <- function(df) {
  # Apply the cleaning process to all column names
  colnames(df) <- gsub("^[X]", "", colnames(df)) # Remove first "X" if present - this is a Python artifact from pre-processing
  colnames(df) <- gsub("\\.", "-", colnames(df))  # Replace "." with "-"
  
  return(df)
}

# Function to clean up empty columns
remove_empty_columns <- function(df) {
  # Check for columns where all entries are "--"
  cols_to_keep <- sapply(df, function(col) {
    !all(col == "'--")
  })
  
  # Subset the dataframe to keep only the relevant columns
  df_cleaned <- df[, cols_to_keep]
  
  return(df_cleaned)
}
```

# Data harmonization

```{r}
expression.clean <- clean_column_names(expression.clean)
clinical <- remove_empty_columns(clinical)
```

```{r}
# Keep only the sample name from the file names
mappings <- mappings %>%
  mutate(File.Name = gsub(".rna_seq.augmented_star_gene_counts.tsv", "", File.Name)) %>%
  select(2, 6)
```

```{r}
# Create dummy variables for survival analysis and calculate OS.time
clinical <- clinical %>%
  mutate(
    OS = ifelse(vital_status == "Dead", 1, 0),
    OS.time = ifelse(days_to_death != "'--", days_to_death, days_to_last_follow_up),
    OS.time = ifelse(OS.time == "'--", NA, as.numeric(OS.time)),
    OS.time.years = OS.time / 365
  ) %>%
  drop_na(OS.time)
```

```{r}
# Clean up the expression data and set gene symbols as row names
gene.names <- expression.clean$gene_name
expression.clean <- expression.clean %>%
  select(-gene_name) %>%
  as.matrix() %>%
  `rownames<-`(gene.names)
```

```{r}
# Convert to matrix - required by GSVA
class(expression.clean) <- "numeric"
```

Genes of Interest (GOIs) list

```{r}
# Define the list of genes of interest (GOIs)
goi <- list(c('OLR1', 'HILPDA'),
            c('IL1A', 'CCL20', 'ERI2'))
```

```{r}
# Define the names of the GOI groups (the groups should be equal to the GOIs defined above)
sig_names <- c("GOIs_1", 
               "GOIs_2")
```

```{r}
# Name the GOIs list per grouping name (see above)
names(goi) <- sig_names
```

Run GSVA

```{r}
# Run the GSVA and transpose the results for easier processing - NEW
gsvaPar <- gsvaParam(expression.clean, goi)
gsva.res <- gsva(gsvaPar, verbose=FALSE)
res <- as.data.frame(t(gsva.res), stringsAsFactors = FALSE)
res$File.Name<- rownames(res)
```

Sanitize GSVA results

```{r}
# merge gois with mappings to allow integration with clinical data
gsva.final <- merge(mappings, res, by = "File.Name")

# rename case id col - allows merging
names(gsva.final)[names(gsva.final) == 'Case.ID'] <- 'case_submitter_id'
```

Join GSVA results with clinical data

```{r}
# de-duplicate ckinical
clinical.dedup <- unique(clinical[ , c(1, 2, 36, 37, 38)])

clinical.final <- merge(gsva.final, clinical.dedup, by = "case_submitter_id")
```

Find optimal cutpoints for the survival analysis

```{r}
# Define the cutpoint - to be used for the ranking: high/low
surv_cut <- surv_cutpoint(
  clinical.final,
  time = "OS.time",
  event = "OS",
  variables = sig_names
)
# Check the results
summary(surv_cut)
```

Initialize variables for the ploting loop

```{r}
# Initialize a counter (to be used in the loop below)
counter <- 1

# add method to grid.draw (needed for serialized rendering of the plots - causes error otherwise)
grid.draw.ggsurvplot <- function(x){
  survminer:::print.ggsurvplot(x, newpage = FALSE)
}

# Define an output path
out_path <- "/home/fotakis/myScratch/projects/Sophie_Patti/figures/"
```


