---
title: "TCGA_PRAD_CoxReg"
author: "Georgios Fotakis"
date: "2025-01-23"
output: html_document
---

Load libraries

```{r setup, include=FALSE}
library(survival)
library(survminer)
library(dplyr)
library(GSVA)
library(tidyr)
library(conflicted)
conflict_prefer("select", "dplyr")
```

Load in the data

```{r}
clinical <- read.csv2("/home/fotakis/myScratch/projects/Natalie/TCGA_PRAD/data/clinical.tsv",
                      header = T,
                      sep = "\t")

expression.clean <- read.csv2("/home/fotakis/myScratch/projects/Natalie/TCGA_PRAD/data/total_counts_pats_final/PRAD_RAW_counts.tsv",
                              header = T,
                              sep = "\t")

mappings <- read.csv("/home/fotakis/myScratch/projects/Natalie/TCGA_PRAD/data/gdc_sample_sheet.2025-01-10.tsv",
                     header = T,
                     sep = "\t")
```

Helper functions

```{r}

# Function to clean up the column names
clean_column_names <- function(df) {
  # Apply the cleaning process to all column names
  colnames(df) <- gsub("^[X]", "", colnames(df)) # Remove first "X" if present - this is a Python artifact from pre-processing
  colnames(df) <- gsub("\\.", "-", colnames(df))  # Replace "." with "-"
  
  return(df)
}

# Function to clean up empty columns
remove_empty_columns <- function(df) {
  # Check for columns where all entries are "--"
  cols_to_keep <- sapply(df, function(col) {
    !all(col == "'--")
  })
  
  # Subset the dataframe to keep only the relevant columns
  df_cleaned <- df[, cols_to_keep]
  
  return(df_cleaned)
}
```

Data harmonization

```{r}
# Data harmonization
expression.clean <- clean_column_names(expression.clean)
clinical <- remove_empty_columns(clinical)

# Keep only the sample name from the file names
mappings <- mappings %>%
  mutate(File.Name = gsub(".rna_seq.augmented_star_gene_counts.tsv", "", File.Name)) %>%
  select(2, 6)
```

Dummy variables - OS

```{r}
# Create dummy variables for survival analysis and calculate OS.time
clinical <- clinical %>%
  mutate(
    OS = ifelse(vital_status == "Dead", 1, 0),
    OS.time = ifelse(days_to_death != "'--", days_to_death, days_to_last_follow_up),
    OS.time = ifelse(OS.time == "'--", NA, as.numeric(OS.time)),
    OS.time.years = OS.time / 365
  ) %>%
  drop_na(OS.time)
```

Dummy variables - PFS

```{r}
# Create dummy variables for survival analysis and calculate OS.time
clinical <- clinical %>%
  mutate(
    PFS = ifelse(biochemical_recurrence == "YES", 1, 0),
    PFS = ifelse(is.na(PFS), 0, PFS),
    PFS = ifelse(OS == 1, 1, PFS),
    PFS.time = ifelse(is.na(days_to_first_biochemical_recurrence), days_to_last_follow_up, days_to_first_biochemical_recurrence),
    PFS.time = ifelse(OS == 1, OS.time, as.numeric(PFS.time)),
    PFS.time.years = PFS.time / 365
  ) %>%
  drop_na(PFS.time)
```
