---
title: "TCGA SKCM single gene analysis"
author: "Georgios Fotakis"
date: "2024-11-13"
output: html_document
---

Load libraries

```{r include=FALSE}
library(survival)
library(survminer)
library(dplyr)
library(GSVA)
library(tidyr)
library(conflicted)
conflict_prefer("select", "dplyr")
```

Load in the data

```{r}
clinical <- read.csv2("/home/fotakis/myScratch/projects/Sophie_Patti/clinical/clinical.tsv",
                      header = T,
                      sep = "\t")

expression.clean <- read.csv2("/home/fotakis/myScratch/projects/Sophie_Patti/counts_total/SKCM_TPM.tsv",
                              header = T,
                              sep = "\t")

mappings <- read.csv("/home/fotakis/myScratch/projects/Sophie_Patti/gdc_sample_sheet.2024-10-14.tsv",
                     header = T,
                     sep = "\t")
```

Functions

```{r}
# Function to clean upthe column names
clean_column_names <- function(df) {
  # Apply the cleaning process to all column names
  colnames(df) <- gsub("^[X]", "", colnames(df)) # Remove first "X" if present - this is a Python artifact from pre-processing
  colnames(df) <- gsub("\\.", "-", colnames(df))  # Replace "." with "-"
  
  return(df)
}

# Function to clean up empty columns
remove_empty_columns <- function(df) {
  # Check for columns where all entries are "--"
  cols_to_keep <- sapply(df, function(col) {
    !all(col == "'--")
  })
  
  # Subset the dataframe to keep only the relevant columns
  df_cleaned <- df[, cols_to_keep]
  
  return(df_cleaned)
}

```


Data harmonization

```{r}
expression.clean <- clean_column_names(expression.clean)
clinical <- remove_empty_columns(clinical)

# Keep only the sample name from the file names
mappings <- mappings %>%
  mutate(File.Name = gsub(".rna_seq.augmented_star_gene_counts.tsv", "", File.Name)) %>%
  select(2, 6)

# Create dummy variables for survival analysis and calculate OS.time
clinical <- clinical %>%
  mutate(
    OS = ifelse(vital_status == "Dead", 1, 0),
    OS.time = ifelse(days_to_death != "'--", days_to_death, days_to_last_follow_up),
    OS.time = ifelse(OS.time == "'--", NA, as.numeric(OS.time)),
    OS.time.years = OS.time / 365
  ) %>%
  drop_na(OS.time)

# Clean up the expression data and set gene symbols as row names
gene.names <- expression.clean$gene_name
expression.clean <- expression.clean %>%
  select(-gene_name) %>%
  as.matrix() %>%
  `rownames<-`(gene.names)

# Convert to matrix - required by GSVA
class(expression.clean) <- "numeric"
```

Prepare input for the survival model

```{r}
# Define the gene of interest (GOI)
goi <- "OLR1"

# create a dataframe from the counts matrix
goi_df <- data.frame(
  'File.Name' = colnames(expression.clean),
  'temp' = expression.clean[goi, ]
)

# rename the GOI expression column
colnames(goi_df)[2] <- goi

# merge goi with mappings to allow integration with clinical data
goi.final <- merge(mappings, goi_df, by = "File.Name")
# rename case id col - allows merging
names(goi.final)[names(goi.final) == 'Case.ID'] <- 'case_submitter_id'

# de-duplicate ckinical
clinical.dedup <- unique(clinical[ , c(1, 2, 36, 37, 38)])

# Mege the dataframes
clinical.final <- merge(goi.final, clinical.dedup, by = "case_submitter_id")
```

Compute optimal cutpoint

```{r}
# Define the cutpoint - to be used for the ranking: high/low
surv_cut <- surv_cutpoint(
  clinical.final,
  time = "OS.time.years",
  event = "OS",
  variables = c(goi)
)
summary(surv_cut)
```

Create the dummy variables for the survival model

```{r}
# Create fsctorial vars (high/low) and fit the survival model
clinical.final$GOI.exp <- factor(ifelse(clinical.final[[goi]] > summary(surv_cut)[1, 1], "high", "low"))
```

Fit the survival model to the data

```{r}
fit <- survfit(Surv(time = OS.time.years ,event =  OS) ~ GOI.exp, data = clinical.final)
```

Plot and save the results

```{r}
# Plotting function
survp <- ggsurvplot(fit,
           pval = TRUE,
           conf.int = FALSE,
           risk.table = T, # Add risk table
           risk.table.col = "strata", # Change risk table color by groups
           linetype = "strata", # Change line type by groups
           surv.median.line = "hv", # Specify median survival
           ggtheme = theme_bw(), # Change ggplot2 theme
           # palette = c("red", "blue"), # set the color palette - default if left commented 
           xlab = "OS in years",   # customize X axis label.
           legend.title = paste0(goi, " expression"),
           legend.labs = c("High", "Low"),
           ylab = "Overall Survival (OS)")

# Visualize the results
print(survp)

# Define an output path
out_path <- "/home/fotakis/myScratch/projects/Sophie_Patti/figures/"

# Save the plot (as PNG and SVG)
for (suffix in c("png","svg")) {
  ggsave(filename = paste0(out_path,"surv_",goi,".", suffix),
         survp,
         device = suffix,
         dpi=600,
  )
}
```




